#! /bin/bash

if [ ! -d ~/notflix-backup ]; then
    mkdir ~/notflix-backup
fi

cp /config ~/notflix-backup/
touch ~/notflix-backup/timestamp

zip -rq notflix-backup.zip ~/notflix-backup

rm -rf ~/notflix-backup
