version: '2'
services:
  base:
    image: phusion/baseimage
    container_name: base
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/server:/media
      - /data/torrent:/downloads
    restart: always
  torrent:
    image: diameter/rtorrent-rutorrent:64
    container_name: torrent
    volumes_from:
      - base
    ports:
      - 5500:80
      - 49160:49160/udp
      - 49161:49161
    restart: always
  usenet:
    image: linuxserver/sabnzbd
    container_name: usenet
    volumes_from:
      - base
    volumes:
      - /config/sabnzbd:/config
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 5510:8080
      - 9090:9090
    restart: always
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    volumes_from:
      - base
    volumes:
      - /config/couchpotato:/config
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 5520:5050
    restart: always
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes_from:
      - base
    volumes:
      - /config/sonarr:/config
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 5530:8989
    restart: always
  ombi:
    image: rogueosb/ombi
    container_name: ombi
    volumes_from:
      - base
    volumes:
      - /config/plexrequests:/config
    ports:
      - 5540:3579
    restart: always
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes_from:
      - base
    volumes:
      - /data/plex/transcode:/transcode
      - /config/plex:/config
    environment:
      - PGID=1000
      - PUID=1000
      - VERSION=plexpass
      - TZ=America/Denver
    ports:
        - 32400:32400
        - 32400:32400/udp
        - 32469:32469/udp
        - 5353:5353/udp
        - 1900:1900/udp
    restart: always
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    volumes_from:
      - base
    volumes:
      - /config/plexpy:/config
      - /data/plexpy/logs
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
    ports:
      - 5550:8181
    restart: always
