#! /bin/bash

if [ ! -d ~/notflix-backup ]; then
    mkdir ~/notflix-backup
fi

unzip notflix-backup.zip

#cp --parents ~/notflix-backup/config/couchpotato/config.ini /
#cp --parents ~/notflix-backup/config/sonarr/config.xml /
#cp --parents ~/notflix-backup/config/plexpy/config.ini /
#cp --parents ~/notflix-backup/config/plex/Library/Application\ Support/Plex\ Media\ Server/Preferences.xml /

rm -rf ~/notflix-backup
